function interfata(A,R,T,N,Vt,Is)

fig=figure('Name',' Circuite neliniare cu AO');
    set(fig,'Numbertitle','off');
    set(fig,'Color',[0.8 0.8 0.8]);
    set(fig,'Units','normalized');
    set(fig,'Position',[0.1 0.1 0.7 0.7]);
    set(fig,'Tag','fereastra1');
meniu=uimenu('Label','Documentatie','ForegroundColor','r'); 
uimenu(meniu, 'Label','Circuite','Callback',cat(2,'open ','Circuite.pdf')); 
uimenu(meniu, 'Label','Autor','Callback',cat(2,'open ','Autor.pdf'));
uimenu(meniu, 'Label','Bibliografie','Callback',cat(2,'open ','Bibliografie.pdf'));
left=0.12;
bottom=0.7;
width=0.1;
height=0.05;
Panel_semnal=uipanel('Visible','on',...
                     'BackgroundColor','white',...
                     'ForegroundColor','black',...
                     'Title','Semnal de intrare',...
                     'FontSize',11,...
                     'TitlePosition','centertop',...
                     'Position',[left+0.12 bottom-0.30 width+0.08 height+0.38]);
uicontrol('Style','pushbutton',...
            'Units','normalized',...
            'Position',[0.7 0.15 0.15 0.1],...
            'String','Circuitul urmator',...
            'Callback','close;interfata2(A,R,T,N,Vt,Is)');
uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.78 0.4 0.12],...
            'String', T,...
            'Callback','T=str2num(get(gco,''string'')),close;interfata(A,R,T,N,Vt,Is);',...
            'Parent',Panel_semnal);
uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.72 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'T [s]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',Panel_semnal);
            
uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.58 0.4 0.12],...
            'String', A,...
            'Callback','A=str2num(get(gco,''string'')),close;interfata(A,R,T,N,Vt,Is);',...
            'Parent',Panel_semnal);
uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.52 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'A [V]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',Panel_semnal);
uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.38 0.4 0.12],...
            'String', N,...
            'Callback','N=str2num(get(gco,''string'')),close;interfata(A,R,T,N,Vt,Is);',...
            'Parent',Panel_semnal);
uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.32 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'N ',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',Panel_semnal);
RadioGroup = uibuttongroup('Visible','on',...
                     'BackgroundColor','white',...
                     'ForegroundColor','black',...
                     'Title','Tipul semnalului',...
                     'FontSize',10,...
                     'TitlePosition','centertop',...
                     'Tag','radiobutton',...
                     'Position',[0.05 0.0 0.9 0.35],...
                     'Parent',Panel_semnal);                  
RadioB1=uicontrol('Style','radiobutton',...
                  'Units','normalized',...
                  'BackgroundColor','white',...
                  'ForegroundColor','black',...
                  'Position',[0.15 0.65 0.75 0.2],...
                  'String','Sinus',...
                  'Parent',RadioGroup);                 
uicontrol('Style','radiobutton',...
                  'Units','normalized',...
                  'BackgroundColor','white',...
                  'ForegroundColor','black',...
                  'Position',[0.15 0.35 0.8 0.3],...
                  'String','Dreptunghi',...
                  'Parent',RadioGroup);           
uicontrol('Style','radiobutton',...
                  'Units','normalized',...
                  'BackgroundColor','white',...
                  'ForegroundColor','black',...
                  'Position',[0.15 0.05 0.8 0.3],...
                  'String','Triunghi',...
                  'Parent',RadioGroup); 
set(RadioGroup,'SelectedObject',RadioB1); 
set(RadioGroup,'SelectionChangeFcn',' grafic(A,R,T,N,Vt,Is)');
Panel_circuit=uipanel('Visible','on',...
                     'BackgroundColor','white',...
                     'ForegroundColor','black',...
                     'Title','Parametrii circuitului',...
                     'FontSize',11,...
                     'TitlePosition','centertop',...
                     'Position',[left-0.07 bottom-0.30 width+0.08 height+0.38]);
uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.78 0.4 0.12],...
            'String', R,...
            'Callback','R=str2num(get(gco,''string'')),close;interfata(A,R,T,N,Vt,Is);',...
            'Parent',Panel_circuit);
uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.72 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'R [ohm]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',Panel_circuit);
uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.58 0.4 0.12],...
            'String', Vt,...
            'Callback','Vt=str2num(get(gco,''string'')),close;interfata(A,R,T,N,Vt,Is);',...
            'Parent',Panel_circuit);
uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.52 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'Vt [ V]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',Panel_circuit);
uicontrol('Style','edit',...
            'Units','normalized',...
            'Position',[0.5 0.38 0.4 0.12],...
            'String', Is,...
            'Callback','Is=str2num(get(gco,''string'')),close;interfata(A,R,T,N,Vt,Is);',...
            'Parent',Panel_circuit),....
uicontrol('Style','text',...
                'Units','normalized',...
                'Position',[0.08 0.32 0.4 0.15],...
                'BackgroundColor','white',...
                'ForegroundColor','red',...
                'String', 'Is [A]',...
                'Fontsize', 9,...
                'FontWeight','demi',...
                'HorizontalAlignment','left',...
                'Parent',Panel_circuit);

uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'BackgroundColor','white',...
                'ForegroundColor','black',...
                'Position',[left-0.07 bottom+0.15 0.4 0.1],...
                'String', 'Circuit de logaritmare cu amplificator operational',...
                'Fontsize', 17,...
                'FontWeight','demi',...
                'HorizontalAlignment','center'); 
 grafic(A,R,T,N,Vt,Is);
end
